### ISSUE TITLE
Jenkins master deletes slaves before they get a chance to connect

### ISSUE THREAD

**Issue by thesamet** [jenkinsci/kubernetes-plugin#20] opened 2015-10-05 20:26 UTC
We are seeing a lot of dead Jenkins slave pods. This seems to happen under load.

When I go to the master logs and look for an id of a dead slave id I find this:

```
Oct 05, 2015 7:04:16 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for slave 78ff8795-a478-412e-9ebe-f05d6a22d14c
Oct 05, 2015 07:04:16 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
INFO: Created Pod: 78ff8795-a478-412e-9ebe-f05d6a22d14c
Oct 05, 2015 07:04:16 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
INFO: Waiting for Pod to be scheduled (0/100): 78ff8795-a478-412e-9ebe-f05d6a22d14c
Oct 05, 2015 07:04:22 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
INFO: Waiting for Pod to be scheduled (1/100): 78ff8795-a478-412e-9ebe-f05d6a22d14c
Oct 05, 2015 12:04:59 PM jenkins.slaves.JnlpSlaveHandshake error
WARNING: TCP slave agent connection handler #228 with /10.78.46.125:47207 is aborted: Unrecognized name: 78ff8795-a478-412e-9ebe-f05d6a22d14c
Oct 05, 2015 07:05:01 PM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFO: Accepted connection #229 from /10.78.46.125:47210
Oct 05, 2015 07:05:01 PM jenkins.slaves.JnlpSlaveHandshake error
WARNING: TCP slave agent connection handler #229 with /10.78.46.125:47210 is aborted: No such slave: 78ff8795-a478-412e-9ebe-f05d6a22d14c
```

In the logs of the slaves:

```
INFO: Trying protocol: JNLP-connect
Oct 05, 2015 7:05:01 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server didn't understand the protocol: No such slave: 78ff8795-a478-412e-9ebe-f05d6a22d14c
Oct 05, 2015 7:05:01 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to ci:35823
Oct 05, 2015 7:05:01 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:297)
	at hudson.remoting.Engine.run(Engine.java:268)
```

This is what I see:
- The master is trying to terminate the slave before it even creates the pod, so it loses track of the slave's name.
- It then creates the slave pod.
- The slave connects to the master and being told that it doesn't recognize its name.

**Comment by flandr** [comment] 2015-10-21 15:11
I didn't notice this open issue when I ran into the same problem; fixed yesterday in pull #26

**Comment by carlossg** [comment] 2015-10-21 15:57
closing with #26, please reopen if not fixed yet

**Closed by carlossg** 2015-10-21 15:57 UTC

**Comment by flandr** [comment] 2015-10-21 19:08
Hmm, on second thought, if the pod takes > 1 minute to spin up this problem still remains when #26 is applied. I just ran into this because I'm deploying a new ridiculously large build image. Perhaps this parameter should be configurable?

**Comment by itomaldonado** [comment] 2015-10-27 22:37
Hey, not sure if I should open a new issue, but I wanted to show that I am still seeing the same problem as @thesamet and I am using 0.4.1 and I am using the default values. But in my case the nodes are being deleted/terminated by Jenkins immediately. 

Finally, I wanted to note, this happens when more than one job is scheduled to run at the same time, for some reason there is a weird race condition?

Anyway, if you need me to open a new issue, let me know.

Jenkins Logs:
```
Oct 27, 2015 10:27:08 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Kubernetes Pod Template from Kubernetes-Jenkins-Cluster with 1 executors. Remaining excess workload: -0.003
Oct 27, 2015 10:27:08 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for slave 8b2fc04c2652b
Oct 27, 2015 10:27:08 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
SEVERE: Failure to terminate instance for slave 8b2fc04c2652b
javax.ws.rs.WebApplicationException: HTTP 404 pods "8b2fc04c2652b" not found
        at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:40)
        at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:31)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:302)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:725)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:683)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)
        at com.sun.proxy.$Proxy64.deletePod(Unknown Source)
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave._terminate(KubernetesSlave.java:75)
        at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:67)
        at org.jenkinsci.plugins.durabletask.executors.OnceRetentionStrategy$1.run(OnceRetentionStrategy.java:130)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

You see a node being created, then immediately the _terminate being called since kubernetes does not have the container up and running it fails, of course. Also, note the image is already loaded in the Kubernetes nodes, so this pod comes up almost immediately as well.

**Comment by flandr** [comment] 2015-10-27 22:48
This looks like the same thing to me, @itomaldonado; if you look at my comments in #26 the root cause of `_terminate` being invoked turns out to be the `OnceRetentionStrategy` having a too-low timeout and running before the pod has a chance to start up. I changed the retention period to one minute in that patch; I'm working up a patch to make that a configuration option for when you have _very large_ images that take over a minute to pull & start. 

Perhaps try building the plugin off of the master branch and see if that fixes your problem?

**Comment by itomaldonado** [comment] 2015-10-28 00:16
Oh, I thought that version 0.4.1 of the plugin included this fix. Let my try pulling the master and using that. Will comment again once done.

**Comment by itomaldonado** [comment] 2015-10-28 02:22
Yes, I am using this version 728687193fac45d47bb6e35227923a62c1e325ea and I think it already has #26 on it.

I can't run the image again, but I'll run it tomorrow morning with the property set-up (not using defaults) and see if that does anything.

**Comment by itomaldonado** [comment] 2015-10-28 02:24
Never mind, I just saw that master is way ahead. I'll try it with master tomorrow.
